server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
spring:
  mustache:
    suffix: .html
  task:
    scheduling:
      pool:
        size: 2
      shutdown:
        await-termination: true
    execution:
      shutdown:
        await-termination: true
  data:
    mongodb:
      port: 27017
  cache:
    cache-names:
      - "github-users"
    type: caffeine
    caffeine:
      spec:
        maximumSize: 1000
        expireAfterAccess: 1h
application:
  metrics:
    repository:
      database: "ghr-metrics"
      collection: "request_count"
    publisher:
      flush_interval_ms: 1000
